In [1]:
library(tidyverse)
library(data.table)
library(plotly)
library(glmnet)

Warning message:
“package ‘ggplot2’ was built under R version 4.4.3”
Warning message:
“package ‘tibble’ was built under R version 4.4.3”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Warning message:
“package ‘data.table’ was built under R version 4.4.3”

Attaching package: ‘data.table’


The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose


Warning message:
“package ‘plotly’ was built under R version 4.4.3”

Attaching package: ‘plotly’


The following object is masked from ‘package:ggplot2’:

    last_plot


The following object is masked from ‘package:stats’:

    filter


The following object is masked from ‘package:graphics’:

    layout


Warning message:
“package ‘glmnet’ was built under R version 4.4.3”
Loading required package: Matrix

Warning message:
“package ‘Matrix’ was built under R version 4.4.3”

Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack


Loaded glmnet 4.1-10

In [2]:
process_df <- function(df) {
    df <- fread(df)
    df$GO_ID <- as.factor(df$GO_ID)
    df <- df %>% pivot_longer(cols = c("div_d_gamb", "div_d_colu", "div_d_arab"), names_to = "Species", values_to = "Polymorphism")
    df$Species <- as.factor(df$Species)
    df <- df[!is.na(df$Polymorphism) & !is.infinite(df$Polymorphism) & df$Polymorphism > 0,]
    df$Level <- as.factor(df$Level)
    return(df)
}

lambda_cv <- function(gomatrix, df, alpha=1) {
    #df_matrix <- model.matrix(~GO_ID, data=df)

    divergence_vector <- df$residuals
    lambda_seq <- 10^seq(3, -3, by=-0.1)

    cv_output <- cv.glmnet(gomatrix, divergence_vector, alpha=alpha, lambda=lambda_seq, nfolds=10)
    best_lambda <- cv_output$lambda.min
    return(best_lambda)
}

lasso_regress <- function(gomatrix, df, alpha, lambda){
    #df_matrix <- model.matrix(~GO_ID, data=df)
    divergence_vector <- df$residuals

    lasso_model <- glmnet(gomatrix, divergence_vector, alpha=alpha, lambda=lambda)
    coefficients <- as.data.frame(as.matrix(coef(lasso_model)))
    colnames(coefficients) <- "Coefficient"
    coefficients <- rownames_to_column(coefficients, var="GO_ID")
    non_zero_coefficients <- coefficients[coefficients$Coefficient != 0,]
    return(non_zero_coefficients)
}

In [3]:
fdf <- process_df('out/gamb_colu_arab_Function_terms_stats.csv')
fdfG <- fdf[fdf$Species == "div_d_gamb",]
fdfA <- fdf[fdf$Species == "div_d_arab",]
fdfC <- fdf[fdf$Species == "div_d_colu",]
covar <- fread('out/gamb/gene_covariates.txt')
fdfG <- merge(covar, fdfG)
fdfG$Sexchrom <- FALSE
fdfG[fdfG$Chromosome == "AgamP4_X",]$Sexchrom <- TRUE
nrow(fdfG)

[1] 27230

In [4]:
compmat <- fread('out/gamb_colu_arab_Function_edge_matrix.txt')
compmat <- t(as.matrix(compmat))
compmat <- as.data.frame(compmat)
names(compmat) <- as.character(unlist(compmat[1,]))
compmat <- compmat[-1,]
compmat <- tibble::rownames_to_column(compmat, var="Gene")

In [5]:
mdf <- merge(fdfG, compmat)

In [6]:
resmodel <- lm(Polymorphism ~ GC_Content + Sexchrom + Length, data=mdf)
mdf$residuals <- resmodel$residuals

In [ ]:
L <- lambda_cv(as.matrix(select(mdf, contains("GO:"))), mdf, alpha=1)
print(L)
coefs <- lasso_regress(as.matrix(select(mdf, contains("GO:"))), mdf, alpha=1, lambda=L)
coefs %>% arrange(desc(Coefficient))

In [ ]:
cdf <- process_df('out/gamb_colu_arab_Component_terms_stats.csv')
cdfG <- cdf[cdf$Species == "div_d_gamb",]
cdfA <- cdf[cdf$Species == "div_d_arab",]
cdfC <- cdf[cdf$Species == "div_d_colu",]
covar <- fread('out/gamb/gene_covariates.txt')
cdfG <- merge(covar, cdfG)
cdfG$Sexchrom <- FALSE
cdfG[cdfG$Chromosome == "AgamP4_X",]$Sexchrom <- TRUE
head(cdfG)

  Gene       Chromosome Start  End    Length GC_Content GO_ID
1 AGAP000005 AgamP4_X    32382  38843  6462  0.42108    GO:0005694
2 AGAP000005 AgamP4_X    32382  38843  6462  0.42108    GO:0005634
3 AGAP000007 AgamP4_X    83817  88773  4957  0.57938    GO:0005886
4 AGAP000008 AgamP4_X    90142  94903  4762  0.47249    GO:0016020
5 AGAP000013 AgamP4_X   148957 163951 14995  0.48149    GO:0005886
6 AGAP000013 AgamP4_X   148957 163951 14995  0.48149    GO:0016020
  Transcript    gene_pi_gamb gene_pi_colu ⋯ ss_d_colu ss_d_arab ns_d_gamb
1 AGAP000005-RA 0.003533088  0.001775797  ⋯ -1.516408 -2.408548 -2.744734
2 AGAP000005-RA 0.003533088  0.001775797  ⋯ -1.516408 -2.408548 -2.744734
3 AGAP000007-RA 0.003425350  0.001166049  ⋯ -2.575448 -2.347921 -2.774236
4 AGAP000008-RA 0.003825916  0.003345175  ⋯ -1.992269 -1.728950 -2.731823
5 AGAP000013-RA 0.009004225  0.007944258  ⋯ -1.907544 -2.250249 -2.725971
6 AGAP000013-RA 0.009004225  0.007944258  ⋯ -1.907544 -2.250249 -2.725971
  ns_d_colu ns_d_arab Level Depth Species    Polymorphism Sexchrom
1 -2.364059 -2.528620 5     5     div_d_gamb 1.034682     TRUE
2 -2.364059 -2.528620 5     5     div_d_gamb 1.034682     TRUE
3 -2.750270 -2.541279 3     3     div_d_gamb 1.048937     TRUE
4 -2.399738 -2.145399 2     2     div_d_gamb 1.044263     TRUE
5 -2.352487 -2.594408 3     3     div_d_gamb 1.067929     TRUE
6 -2.352487 -2.594408 2     2     div_d_gamb 1.067929     TRUE

In [ ]:
compmat <- fread('out/gamb_colu_arab_Component_edge_matrix.txt')
compmat <- t(as.matrix(compmat))
compmat <- as.data.frame(compmat)
names(compmat) <- as.character(unlist(compmat[1,]))
compmat <- compmat[-1,]
compmat <- tibble::rownames_to_column(compmat, var="Gene")

In [ ]:
mdf <- merge(cdfG, compmat)

In [ ]:
resmodel <- lm(Polymorphism ~ GC_Content + Sexchrom + Length, data=mdf)
mdf$residuals <- resmodel$residuals

In [ ]:
L <- lambda_cv(as.matrix(select(mdf, contains("GO:"))), mdf, alpha=1)
print(L)
coefs <- lasso_regress(as.matrix(select(mdf, contains("GO:"))), mdf, alpha=1, lambda=L)
coefs %>% arrange(desc(Coefficient))

[1] 0.001

    GO_ID                 Coefficient
1   GO:0099023;GO:0017119 0.6673984
2   GO:0000502;GO:0031595 0.6634245
3   GO:0032045;GO:0071986 0.5967441
4   GO:1990234;GO:0000408 0.5789107
5   GO:0106068;GO:0030915 0.5555424
6   GO:0030684;GO:0030686 0.4866244
7   GO:1990234;GO:0106068 0.4505612
8   GO:0098796;GO:0000506 0.4209724
9   GO:0043227;GO:0065010 0.3793065
10  GO:0098791;GO:0005795 0.3456440
11  GO:0098798;GO:0005763 0.3298789
12  GO:0009295;GO:0042645 0.3248943
13  GO:0110165;GO:0000407 0.2801921
14  GO:0032991;GO:0033061 0.2747473
15  GO:0098798;GO:0005762 0.2702647
16  GO:0000793;GO:0000794 0.2582727
17  GO:0005657;GO:0043596 0.2457708
18  GO:0005819;GO:0072686 0.2359847
19  GO:0005815;GO:0000923 0.2184234
20  GO:0140168;GO:0015030 0.2029873
21  GO:0000151;GO:0031461 0.1983135
22  GO:0098796;GO:0072546 0.1895573
23  GO:0031982;GO:1903561 0.1863401
24  GO:0032991;GO:0097255 0.1797151
25  GO:0032991;GO:0042555 0.1691602
26  GO:0031597;GO:0009376 0.1409702
27  GO:0099023;GO:0000145 0.1278630
28  GO:0070013;GO:0005759 0.1247609
29  GO:0034708;GO:0043527 0.1196836
30  GO:1902494;GO:0071013 0.1141480
⋮   ⋮                     ⋮
453 GO:0031010;GO:0016589 -0.1124537
454 GO:0030424;GO:0042757 -0.1183397
455 GO:0043232;GO:0005814 -0.1200215
456 GO:0098796;GO:0030904 -0.1207015
457 GO:0005811;GO:0005633 -0.1221597
458 GO:0008287;GO:0000159 -0.1298209
459 GO:0140534;GO:0070939 -0.1337694
460 GO:0080008;GO:0031464 -0.1339410
461 GO:0032010;GO:0020020 -0.1385736
462 GO:0005849;GO:0005848 -0.1437875
463 GO:0071256;GO:0005784 -0.1553362
464 GO:0032991;GO:0000974 -0.1562436
465 GO:0140513;GO:0005681 -0.1601874
466 GO:0140513;GO:0031499 -0.1687998
467 GO:0140535;GO:0030015 -0.1712337
468 GO:0090533;GO:0005890 -0.1743299
469 GO:0098796;GO:0071439 -0.1805508
470 GO:0140535;GO:0005956 -0.1827166
471 GO:0032991;GO:0090665 -0.1930745
472 GO:0044391;GO:0015935 -0.1938603
473 GO:0015934;GO:0022625 -0.2004854
474 GO:0099086;GO:0000795 -0.2006628
475 GO:0031970;GO:0005758 -0.2010843
476 GO:1905368;GO:0000124 -0.2042761
477 GO:0140534;GO:0005787 -0.2076629
478 GO:1905354;GO:0031251 -0.2094143
479 GO:0090575;GO:0005672 -0.2190454
480 GO:1902494;GO:0000015 -0.2691333
481 GO:0032991;GO:0098803 -0.2691857
482 GO:1902554;GO:1990316 -0.3178319

In [ ]:
pdf <- process_df('out/gamb_colu_arab_Process_terms_stats.csv')
pdfG <- pdf[pdf$Species == "div_d_gamb",]
pdfA <- pdf[pdf$Species == "div_d_arab",]
pdfC <- pdf[pdf$Species == "div_d_colu",]
covar <- fread('out/gamb/gene_covariates.txt')
pdfG <- merge(covar, pdfG)
pdfG$Sexchrom <- FALSE
pdfG[pdfG$Chromosome == "AgamP4_X",]$Sexchrom <- TRUE
head(pdfG)

  Gene       Chromosome Start  End    Length GC_Content GO_ID
1 AGAP000007 AgamP4_X    83817  88773 4957   0.57938    GO:0007411
2 AGAP000007 AgamP4_X    83817  88773 4957   0.57938    GO:0007155
3 AGAP000008 AgamP4_X    90142  94903 4762   0.47249    GO:0006457
4 AGAP000008 AgamP4_X    90142  94903 4762   0.47249    GO:0009408
5 AGAP000011 AgamP4_X   126414 134756 8343   0.51372    GO:0009081
6 AGAP000012 AgamP4_X   146181 147832 1652   0.56356    GO:0006418
  Transcript    gene_pi_gamb gene_pi_colu ⋯ ss_d_colu ss_d_arab ns_d_gamb
1 AGAP000007-RA 0.003425350  0.001166049  ⋯ -2.575448 -2.347921 -2.774236
2 AGAP000007-RA 0.003425350  0.001166049  ⋯ -2.575448 -2.347921 -2.774236
3 AGAP000008-RA 0.003825916  0.003345175  ⋯ -1.992269 -1.728950 -2.731823
4 AGAP000008-RA 0.003825916  0.003345175  ⋯ -1.992269 -1.728950 -2.731823
5 AGAP000011-RA 0.006897925  0.006560240  ⋯ -1.679237 -1.597132 -2.747789
6 AGAP000012-RA 0.009494305  0.005786689  ⋯ -1.894390 -1.338811 -2.678551
  ns_d_colu ns_d_arab Level Depth Species    Polymorphism Sexchrom
1 -2.750270 -2.541279 8     8     div_d_gamb 1.048937     TRUE
2 -2.750270 -2.541279 2     2     div_d_gamb 1.048937     TRUE
3 -2.399738 -2.145399 2     2     div_d_gamb 1.044263     TRUE
4 -2.399738 -2.145399 3     4     div_d_gamb 1.044263     TRUE
5 -2.465054 -2.101571 5     7     div_d_gamb 1.131270     TRUE
6 -2.312434 -2.448316 7     9     div_d_gamb 1.118706     TRUE

In [ ]:
compmat <- fread('out/gamb_colu_arab_Process_edge_matrix.txt')
compmat <- t(as.matrix(compmat))
compmat <- as.data.frame(compmat)
names(compmat) <- as.character(unlist(compmat[1,]))
compmat <- compmat[-1,]
compmat <- tibble::rownames_to_column(compmat, var="Gene")

In [ ]:
mdf <- merge(pdfG, compmat)

In [ ]:
resmodel <- lm(Polymorphism ~ GC_Content + Sexchrom + Length, data=mdf)
mdf$residuals <- resmodel$residuals

In [ ]:
L <- lambda_cv(as.matrix(select(mdf, contains("GO:"))), mdf, alpha=1)
print(L)
coefs <- lasso_regress(as.matrix(select(mdf, contains("GO:"))), mdf, alpha=1, lambda=L)
coefs %>% arrange(desc(Coefficient))

[1] 0.001

     GO_ID                 Coefficient
1    GO:0016925;GO:1990466 1.1303709
2    GO:0007114;GO:0007120 1.0883579
3    GO:0001510;GO:0036265 0.8396406
4    GO:0051604;GO:0016255 0.7007985
5    GO:0001919;GO:0001920 0.5485378
6    GO:0001101;GO:0043200 0.4216091
7    GO:0006081;GO:0046487 0.4115358
8    GO:0015850;GO:0015918 0.4061660
9    GO:0000740;GO:0007086 0.4025633
10   GO:0051494;GO:0051126 0.3970180
11   GO:0032984;GO:1903259 0.3658582
12   GO:1903432;GO:1904263 0.3655938
13   GO:0006563;GO:0006564 0.3620959
14   GO:0043086;GO:0051346 0.3477772
15   GO:0032006;GO:1903432 0.3370067
16   GO:0006650;GO:0046341 0.3328100
17   GO:0006555;GO:0009087 0.3304009
18   GO:0140694;GO:0051225 0.3225308
19   GO:0046653;GO:0046654 0.3203759
20   GO:0007009;GO:0017121 0.3118493
21   GO:0009060;GO:0006119 0.2896697
22   GO:0048523;GO:0045786 0.2800136
23   GO:0018193;GO:0018208 0.2725724
24   GO:0070585;GO:0045041 0.2650996
25   GO:0043648;GO:0006536 0.2621464
26   GO:0000966;GO:0099116 0.2559883
27   GO:0006101;GO:0019651 0.2538909
28   GO:0000491;GO:0000493 0.2486782
29   GO:0036211;GO:0018149 0.2432603
30   GO:0006418;GO:0006431 0.2333949
⋮    ⋮                     ⋮
1501 GO:0006790;GO:0046500 -0.1396055
1502 GO:0035196;GO:0031053 -0.1410563
1503 GO:0006835;GO:0051938 -0.1411024
1504 GO:0017014;GO:0018119 -0.1444188
1505 GO:0051345;GO:0043547 -0.1444612
1506 GO:0006996;GO:0007029 -0.1484620
1507 GO:0003052;GO:0003054 -0.1543786
1508 GO:0034976;GO:0006983 -0.1553317
1509 GO:0006474;GO:0017196 -0.1554741
1510 GO:0000470;GO:0000463 -0.1560611
1511 GO:0006412;GO:0002181 -0.1577527
1512 GO:0006778;GO:0046501 -0.1581004
1513 GO:0035383;GO:0035384 -0.1612155
1514 GO:1903047;GO:0007093 -0.1641735
1515 GO:0007186;GO:0007188 -0.1652882
1516 GO:0032446;GO:0045116 -0.1754777
1517 GO:0019646;GO:0006123 -0.1771721
1518 GO:0006259;GO:0006285 -0.1803695
1519 GO:0009084;GO:0006526 -0.1819854
1520 GO:0022613;GO:0042254 -0.2173917
1521 GO:0018011;GO:0018012 -0.2209941
1522 GO:0001525;GO:0002040 -0.2324397
1523 GO:0031570;GO:0000077 -0.2346971
1524 GO:0032008;GO:1904515 -0.2471956
1525 GO:0007060;GO:0051308 -0.2518450
1526 GO:0032984;GO:0051261 -0.3758859
1527 GO:0032984;GO:0097352 -0.3760376
1528 GO:0006474;GO:0017190 -0.4010470
1529 GO:0032006;GO:1903939 -0.4255972
1530 GO:0036265;GO:0106004 -0.9366792